### ISSUE TITLE
ER: New Ringdown V1.2 Updates

### ISSUE THREAD

**Issue by joekaylor** [sfbrigade/bats-server#165] opened 2022-07-06 22:34 UTC
Single New Ringdown
When a new ringdown is received, a modal opens from the bottom of which ever screen the user is currently on, and a skrim overlays the background.

Expanded Ringdown
When the user taps ‘more info’, the ringdown summary card expands to reveal additional patient info and a ‘confirm receipt’ button. If the user taps ‘confirm reciept’ on the only remaining ringdown, the modal is closed and the ringdown is added to the queue.

Multiple New Ringdowns
When multiple ringdowns are received before a nurse user has confirmed receipt, they are added to a queue, ordered by time received. The 2nd and 3rd ringdowns from the top are disabled until the top ringdown has been confirmed.
After 3 ringdowns, additional are hidden and indicated by the ‘+[N] More’ label. If a patient is offloaded before their ringdown is confirmed, they are removed from the queue.

see new ringdown in Figma V1.2 

https://www.figma.com/file/5FQp0yeFrJOCR4DapnLUG3/RoutED---Ambulance-Destination-Tool?node-id=466%3A9565

**Comment by fwextensions** [comment] 2022-08-29 03:34
@francisli is there a way of triggering multiple ringdowns to test this scenario? 

> When multiple ringdowns are received before a nurse user has confirmed receipt, they are added to a queue, ordered by time received. The 2nd and 3rd ringdowns from the top are disabled until the top ringdown has been confirmed.

**Comment by francisli** [comment] 2022-08-29 18:42
@fwextensions the seed data creates multiple EMS accounts (op.ems, op.ems.1, op.ems.2, etc) that you can use to log in and generate multiple ringdowns manually...

**Comment by fwextensions** [comment] 2022-08-29 21:24
Okay, it looks like the overflow is working as designed:

![image](https://user-images.githubusercontent.com/61631/187301107-c1d6c367-43bd-4753-a1c7-78fbcfdc16f2.png)

However, with PR #220 forcing the overlay to be the height of the viewport, the list won't scroll:

![image](https://user-images.githubusercontent.com/61631/187301226-88451bc2-eeed-4b79-8bbc-0936081c56d1.png)

So that will need to be fixed, but we can close this task.

**Closed by fwextensions** 2022-08-29 21:24 UTC
